"""empty message

Revision ID: 5572a13879c4
Revises: 
Create Date: 2022-03-28 21:09:27.459162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5572a13879c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cf_user_profile',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usid')
    )
    op.create_index(op.f('ix_cf_user_profile_id'), 'cf_user_profile', ['id'], unique=False)
    op.drop_table('user_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('id', mysql.CHAR(length=16), nullable=False),
    sa.Column('pd', mysql.CHAR(length=16), nullable=False),
    sa.Column('email', mysql.CHAR(length=30), nullable=False),
    sa.Column('alcohol', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_cf_user_profile_id'), table_name='cf_user_profile')
    op.drop_table('cf_user_profile')
    # ### end Alembic commands ###
