# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\OneDrive - stu.csust.edu.cn\桌面\Python\network\app\connect.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import views
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget

class Ui_connect(QWidget):

    def __init__(self):
        super(Ui_connect,self).__init__()
        self.setupUi(self)
        self.retranslateUi(self)

    def setupUi(self, connect_ui):
        connect_ui.setObjectName("connect_ui")
        connect_ui.resize(288, 150)
        connect_ui.setFixedSize(288, 150)
        self.formLayout_4 = QtWidgets.QFormLayout(connect_ui)
        self.formLayout_4.setObjectName("formLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.labelSSID = QtWidgets.QLabel(connect_ui)
        self.labelSSID.setObjectName("labelSSID")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelSSID)
        self.editSSID = QtWidgets.QLineEdit(connect_ui)
        self.editSSID.setObjectName("editSSID")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.editSSID)
        self.verticalLayout_2.addLayout(self.formLayout_3)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.labelStatus = QtWidgets.QLabel(connect_ui)
        self.labelStatus.setObjectName("labelStatus")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelStatus)
        self.editStatus = QtWidgets.QLineEdit(connect_ui)
        self.editStatus.setObjectName("editStatus")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.editStatus)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelConnect = QtWidgets.QLabel(connect_ui)
        self.labelConnect.setObjectName("labelConnect")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelConnect)
        self.editConnect = QtWidgets.QLineEdit(connect_ui)
        self.editConnect.setObjectName("editConnect")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.editConnect)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_ylogin = QtWidgets.QPushButton(connect_ui)
        # self.btn_ylogin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_ylogin.setObjectName("btn_ylogin")
        self.verticalLayout.addWidget(self.btn_ylogin)
        # self.btn_hide = QtWidgets.QPushButton(connect_ui)
        # self.btn_hide.setLayoutDirection(QtCore.Qt.LeftToRight)
        # self.btn_hide.setObjectName("btn_hide")
        # self.verticalLayout.addWidget(self.btn_hide)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.formLayout_4.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_3)

        
        self.btn_ylogin.clicked.connect(self.login)

        self.retranslateUi(connect_ui)
        QtCore.QMetaObject.connectSlotsByName(connect_ui)


        self.editStatus.setText((str(views.isOnline())))
        self.editConnect.setText(views.getIP())
        self.editSSID.setText(views.getSSID())

    def login(self):
        while(not views.isOnline()):
            self.editStatus.setText("正在连接")
            self.editConnect.setText("正在连接")
            self.editSSID.setText("正在连接")
            views.login()
        self.editStatus.setText((str(views.isOnline())))
        self.editConnect.setText(views.getIP())
        self.editSSID.setText(views.getSSID())


    def retranslateUi(self, connect):
        _translate = QtCore.QCoreApplication.translate
        connect.setWindowTitle(_translate("connect", "登录"))
        self.labelSSID.setText(_translate("connect", "网络名称："))
        self.labelStatus.setText(_translate("connect", "网络状态："))
        self.labelConnect.setText(_translate("connect", "网络地址："))
        self.btn_ylogin.setText(_translate("connect", "点我连接校园网"))
        # self.btn_hide.setText(_translate("connect", "后台连接"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QWidget()
    ui = Ui_connect()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())